# Generated by Django 3.1.7 on 2021-03-24 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20210323_2222'),
        ('api', '0003_room_current_song'),
    ]

    operations = [
    ]
