# Generated by Django 3.1.7 on 2021-06-03 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='details',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='customer_name',
            new_name='name',
        ),
    ]
