# Generated by Django 3.1.7 on 2021-06-03 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_auto_20210603_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='name',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='feedback',
            old_name='message',
            new_name='details',
        ),
    ]
